### ISSUE TITLE
How do you iterate over query results in view

### ISSUE THREAD

**Issue by AppyCat** [RedisGraph/redisgraph-go#18]
Hi, I'm using the Go Buffalo framework. I'm setting a query result for the view, however the result format does not fit how the view consumes it. Here's my code:

query := `MATCH (p:person)-[v:visited]->(c:country)
                 RETURN p.name, p.age, v.purpose, c.name`
rs, _ := graph.Query(query)
rs.PrettyPrint()
c.Set("rs", rs)

And the view:

<%= for (r) in rs { %>
            <tr>
              <td class="centered">
                <%= r.p.name %>
              </td>
              <td>
                <%= r.p.age %>
              </td>
              <td>
                <%= r.p.status %>
              </td>
              <td>
                <%= r.v.purpose %>
              </td>
              <td>
                <%= r.c.name %>
              </td>
            </tr>
<% } %>

What is the correct way to output the result in an html view with the Go lang driver?

**Comment by swilly22** [comment]
Hi @AppyCat, please see the update readme file, it shows how to iterator over a result set.

**Comment by AppyCat** [comment]
Thank you, I tried that in the view, it throws an error. Here's the code for view and error:

<%= for rs.Next() { %>
            <%= r := rs.Record() %>
            <tr>
              <td class="centered">
                <%= r.GetByIndex(0).(string) %>
              </td>
            </tr>
<% } %>

index.html: line 0: expected next token to be (, got IDENT instead
line 42: no prefix parse function for : found
line 42: no prefix parse function for = found
line 45: no prefix parse function for DOT found

**Comment by swilly22** [comment]
Can you please share the query you're executing, I have a feeling there's a syntax error, please make sure you're checking returned error from graph.query

**Comment by swilly22** [comment]
In addition would you mind sharing your usecase on https://github.com/RedisGraph/RedisGraph/issues/677
Thank you!

**Comment by AppyCat** [comment]
Thanks, here's the query, it pretty prints out fine:

query := `MATCH (p:person)-[v:visited]->(c:country)
              RETURN p.name, p.age, v.purpose, c.name`
rs, _ := graph.Query(query)
rs.PrettyPrint()
c.Set("rs", rs)        // adds to context to pass to view

The use case is for a match making app for recommendations. Am trying to get basics working before applying the schema.

**Comment by swilly22** [comment]
I see, can you please try printing the result-set using the next iterator to the console?

**Comment by AppyCat** [comment]
I think we got to the heart of it :) Here's the error on:

rs.Next().PrettyPrint()

actions/home.go:75:4: rs.Next undefined (type *redisgraph.QueryResult has no field or method Next)

**Comment by swilly22** [comment]
Next returns a Record object, which doesn't have a PrettyPrint method, on a Record you can use the Get* methods

**Comment by AppyCat** [comment]
I've used Get methods in the view, however the problem is the error states the query result has no field or method Next().

Here's my output just using:

rs2 := rs.Next()         // as a test

rs.Next undefined (type *redisgraph.QueryResult has no field or method Next)

**Comment by AppyCat** [comment]
I tried the example on the Github page in a fresh stand alone file, and still get same error on the Next():

./main.go:51:8: rs.Next undefined (type *redisgraph.QueryResult has no field or method Next)
./main.go:53:10: rs.Record undefined (type *redisgraph.QueryResult has no field or method Record)

**Comment by AppyCat** [comment]
Without this code, the example on the readme outputs just fine:

for rs.Next() {
		// Get current record.
		r := rs.Record()

		p_name := r.GetByIndex(0).(string)
		p_age := r.GetByIndex(1).(int)
		c_name := r.GetByIndex(2).(string)
		fmt.Printf("p_name: %s p_age: %d c_name: %s\n", p_name, p_age, c_name)
	}

**Comment by swilly22** [comment]
Please make sure you're using the latest version of redisgraph-go as this API been merged earlier today, I'll suggest removing the library locally and refetching

**Comment by swilly22** [comment]
@AppyCat I've just tagged master as V2.0.1
Please let me know if you're able to use the new Result-Set consumption API

**Comment by AppyCat** [comment]
Thank you for following up. I am able to get the complete result now from Next() in a different app but just need to figure out the syntax on the template used in the Echo library.

{{range .rs}}
        {{.rs := .rs.Record()}}
        {{.rs.Record.GetByIndex(0).(string)}}<br>
{{end}}

Perhaps it may be an idea to save the above in the function as a slice or map, and send that to the view? The logic works in the function, but its not in harmony with some view template libs.

**Comment by swilly22** [comment]
Unfortunately I'm not familiar with `Echo` in my mind it would be worthwhile getting the template syntax right and avoid the double processing and the extra memory overhead of saving the result-set to another slice/map.

**Comment by AppyCat** [comment]
Unfortunately the template lib is very limited in functionality, it won't work with a for loop nor likes Record(), throws an error on the parenthesis. It takes range, but that doesn't work for the output logic.

**Comment by AppyCat** [comment]
Thank you for your help but I am losing far too much time on this. I'm going to have to move on to Neo4j or Agensgraph to get productive vs being stuck on something that should be trivial.

Perhaps you may consider adding a view consumption friendly function to the driver and testing it in the go standard library template.

**Comment by swilly22** [comment]
Alright, can I close this issue?

**Comment by AppyCat** [comment]
I tried the Ruby driver as a comparison, it gives the result as:

cmd = """MATCH (p:person)-[:works]->(e:employer) RETURN p"""
response = r.query(cmd)
@res = response.resultset

And I got the view working as:

<% @res.each_with_index do |r, index| %>
	<%= r[0][0]["name"] %>
	<%= r[0][1]["age"] %><br />
<% end %>

Would it be possible to add a method such as 'resultset' in the Ruby driver?

I'll do a comparison with Neo4j tomorrow. 

The problem may be in Redisgraph itself not providing a better structured result by default or at least options for different styles of output.

**Comment by AppyCat** [comment]
Upon reflection I don't think its realistic to put this code in a view file as many view templates by design have limited functionality.

{{ for rs.Next() }}
   r := rs.Record()
   {{ r.GetByIndex(0).(string) }}
   {{ r.GetByIndex(1).(int) }}
   {{ c_name := r.GetByIndex(2).(string) }}
{{ end }}

The above example croaks on any of the parenthesis.

**Comment by AppyCat** [comment]
I created a slice to use in the view to solve above issue and will put it below in case helpful to anyone else:

type person struct {
	name string
	age  int
	status string
	country string
}

people := []person{}

for rs.Next() {
	r := rs.Record()
	people = append(people, (person{name: r.GetByIndex(0).(string), age: r.GetByIndex(1).(int), status: r.GetByIndex(2).(string), country: r.GetByIndex(3).(string)}))
}

Then pass off people slice to view.
