### ISSUE TITLE
What's the ID property for on Node?

### ISSUE THREAD

**Issue by davisford** [RedisGraph/redisgraph-go#2]
Is this just an [oversight](https://github.com/RedisLabs/redisgraph-go/blob/master/client.go#L57)?

RedisGraph doesn't seem to require such and id, and it isn't ever used for anything?

**Comment by swilly22** [comment]
RedisGraph maintains an internal ID for every graph entity,
you can get it by using the `ID` function
`MATCH (n) RETURN ID(n)`
