### ISSUE TITLE
Question: "Query internal execution time 1.623063" on README.md --> what's the unit?

### ISSUE THREAD

**Issue by kokizzu** [RedisGraph/redisgraph-go#43]
second or millisecond or microsecond or nanosecond?

**Comment by filipecosta90** [comment]
Hi there @kokizzu the internal execution time is given in milliseconds. 
Further info can be found on RedisGraph main docs [Reading statistics section here](https://oss.redislabs.com/redisgraph/client_spec/#reading-statistics).

Closing the issue. Feel free to re-open/add further questions related to the subject.
